sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo $DOCKER_USERNAME
      - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
      - cd nginx
      - docker build -t docker-sonerezh .
      - docker images
      - docker tag docker-sonerezh $DOCKER_USERNAME/docker-sonerezh
      - docker push $DOCKER_USERNAME/docker-sonerezh
